# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Question.create(:title => "Imaginative?",:category=>2)
Question.create(:title => "Helpful?",:category=>4)
Question.create(:title => "Mechanically inclined?",:category=>1 )
Question.create(:title => "Mechanical?",:category=>6)
Question.create(:title => "Methodical?",:category=>6)
Question.create(:title => "Enthusiastic?",:category=>4 )
Question.create(:title => "Energetic?",:category=>5)
Question.create(:title => "Persuasive?",:category=>5)
Question.create(:title => "Free spirit or a rebel?",:category=>3)
Question.create(:title => "Like to figure things out?",:category=>2 )
Question.create(:title => "Intuitive?",:category=>2)
Question.create(:title => "Practical?",:category=>1)
Question.create(:title => "Scientific use information to solve new problems?",:category=>2)
Question.create(:title => "Responsible?",:category=>6)
Question.create(:title => "Athletic?",:category=>4)
Question.create(:title => "Curious?",:category=>2)
Question.create(:title => "Assertive?",:category=>5)
Question.create(:title => "Sociable?",:category=>4)
Question.create(:title => "Friendly?",:category=>4 )
Question.create(:title => "Outgoing?",:category=>4 )
Question.create(:title => "Be outdoors?",:category=>4)
Question.create(:title => "A nature lover?",:category=>4 )
Question.create(:title => "Inventive, original?",:category=>3)
Question.create(:title => "Straight forward?",:category=>1)
Question.create(:title => "Self-confident?",:category=>5)
Question.create(:title => "Able to operate tools and machinery?",:category=>1)
Question.create(:title => "Idealistic?",:category=>1 )
Question.create(:title => "Creative?",:category=>3)
Question.create(:title => "Insightful?",:category=>2 )
Question.create(:title => "Able to do your own thing?",:category=>5)
Question.create(:title => "Precise?",:category=>6)
Question.create(:title => "Efficient?",:category=>6)
Question.create(:title => "Observant?",:category=>2)
Question.create(:title => "Sing, act or dance?",:category=>3 )
Question.create(:title => "Cooperate well with others?",:category=>4)
Question.create(:title => "Teach/train others?",:category=>4 )
Question.create(:title => "Plan and supervise an activity?",:category=>5)
Question.create(:title => "Lead a group?",:category=>5 )
Question.create(:title => "Play a sport?",:category=>1)
Question.create(:title => "Use machines and power tools?",:category=>1 )
Question.create(:title => "Give talks or speeches?",:category=>5)
Question.create(:title => "Play a musical instrument?",:category=>3)
Question.create(:title => "Lead a group discussion?",:category=>5 )
Question.create(:title => "Solve math problems?",:category=>2)
Question.create(:title => "Organize activities and events?",:category=>6 )
Question.create(:title => "Do complex calculations?",:category=>2)
Question.create(:title => "Suggest a better way to accomplish a task?",:category=>2 )
Question.create(:title => "Fix electrical things?",:category=>1)
Question.create(:title => "Operate mechanical equipment or power tools?",:category=>1 )
Question.create(:title => "Tolerate weather conditions?",:category=>1)
Question.create(:title => "Solve mechanical problems?",:category=>1 )
Question.create(:title => "Make original crafts, dinners, school or work projects?",:category=>3)
Question.create(:title => "Express yourself clearly?",:category=>4,)
Question.create(:title => "Sketch, draw, paint?",:category=>3)
Question.create(:title => "Do a lot of paperwork in a short time?",:category=>6 )
Question.create(:title => "Understand science-use information to figure things out?",:category=>2)
Question.create(:title => "Write stories, poetry, music?",:category=>3)
Question.create(:title => "Start projects?",:category=>5)
Question.create(:title => "Design fashions, interiors or quilts?",:category=>3 )
Question.create(:title => "Convince people to do things your way?",:category=>5)
Question.create(:title => "Think abstractly?",:category=>2 )
Question.create(:title => "Write useful business letters?",:category=>5)
Question.create(:title => "Mediate disputes?",:category=>4 )
Question.create(:title => "Sell things or promote ideas?",:category=>5)
Question.create(:title => "Work well within a system?",:category=>6 )
Question.create(:title => "Pitch a tent, an idea?",:category=>1)
Question.create(:title => "Work with young people?",:category=>4 )
Question.create(:title => "Perform experiments?",:category=>2)
Question.create(:title => "Meet important people?",:category=>5)
Question.create(:title => "Be elected to office or make your opinions heard?",:category=>5)
Question.create(:title => "Work in groups?",:category=>4)
Question.create(:title => "Win a leadership or sales award?",:category=>5)
Question.create(:title => "Work independently (by yourself, and with little direction)?",:category=>5)
Question.create(:title => "Participate in meetings?",:category=>4 )
Question.create(:title => "Follow clearly defined procedures?",:category=>6 )
Question.create(:title => "Be responsible for details?",:category=>6)
Question.create(:title => "Keep accurate records?",:category=>6 )
Question.create(:title => "Take photographs?",:category=>3 )
Question.create(:title => "Express your own style?",:category=>3, )
Question.create(:title => "Be physically active?",:category=>1 )
Question.create(:title => "Keep detailed records?",:category=>6)
Question.create(:title => "Work outdoors?",:category=>1 )
Question.create(:title => "Work with numbers?",:category=>2 )
Question.create(:title => "Start your own political campaign?",:category=>5)
Question.create(:title => "Play team sports?",:category=>1 )
Question.create(:title => "Make decisions affecting others?",:category=>5)
Question.create(:title => "Work on crafts, make gifts for friends and relatives?",:category=>3 )
Question.create(:title => "Be in the center of activity?",:category=>5 )
Question.create(:title => "Tinker or work with your hands?",:category=>2 )
Question.create(:title => "Push through to task completion?",:category=>5 )
Question.create(:title => "Read scientific or technical magazines?",:category=>2)
Question.create(:title => "Read fiction, plays, poetry?",:category=>3 )
Question.create(:title => "Work on cars, lawnmowers or sewing machines; repair kids' toys?",:category=>1 )
Question.create(:title => "Help people with problems?",:category=>4)
Question.create(:title => "Make sure things get done?",:category=>5)
Question.create(:title => "Explore ideas?",:category=>3)
Question.create(:title => "Attend concerts, theaters, art exhibits?",:category=>3)